### ISSUE TITLE
ActiveJob support out of the box

### ISSUE THREAD

**Issue by BilalBudhani** [excid3/noticed#1]
Notifications are usually sent via background jobs if we can add opt-in support which makes `noticed` gem to take care of queuing as well then it will be an end to end solution I believe. 

Something like `notify_async` would be nice

E.g: 

```ruby
notification = CommentNotification.new(comment: @comment.to_gid)
notification.notify_async(@comment.post.author)
```

**Comment by excid3** [comment]
Agreed! That's one of my todos. 

I was thinking that we'd probably make `Noticed::Base` inherit from ActiveJob to handle that.

**Comment by BilalBudhani** [comment]
That's a clever idea. How would the API look like then? `notify` will directly call `perform_later` internally?

**Comment by excid3** [comment]
That's exactly what I was imagining. Figured we could just keep it clean and simple that way.

**Comment by excid3** [comment]
Alright, initial prototype of jobs is pushed up. I wrote it so that the entire delivery of the notification is a job. 

Thinking on it, we probably should change that to be each delivery method as it's own job. That way if your SMS fails and the job retries, you wouldn't create duplicate database records or emails.

**Comment by excid3** [comment]
Just pushed b3517e1 that makes each delivery method it's own job so they can be retried independently.

**Comment by BilalBudhani** [comment]
That was super quick @excid3, Thank you!
