### ISSUE TITLE
undefined method 'configs_for' for Rails 5.2

### ISSUE THREAD

**Issue by matteomelotti** [excid3/noticed#106]
The model_generator.rb throw an error while trying to create a model with Rails 5.2
I suppose because the 'configs_for' method is not present inside Rails 5.2

**Comment by excid3** [comment]
cc @lorint

**Comment by lorint** [comment]
Good find, @matteomelotti -- thanks for this.

Have put together what I think could be a straightforward fix -- and it likely works for other cases where someone might name their specification something other than "primary".  This is because instead of being hard-coded to always look for *primary*, now it uses whatever specification Rails has picked as being the active one, which in some cases could be the replica, or even something named completely differently.

Wrote a test for the generator that just confirms that everything works, checking to see that the proper files are written into the dummy application.  It first renames out the app/models/notification.rb to have a file extension of .rbxx, then runs the generator, and finally cleans up by deleting the two files that the generator builds, renaming notification.rbxx back to being notification.rb as a final part of teardown.

Eager to hear what you think.
