### ISSUE TITLE
perform_now undefined method

### ISSUE THREAD

**Issue by muhrizkiakbar** [excid3/noticed#118]
not found method perform_now when i use sidekiq

<img width="1271" alt="Screen Shot 2021-05-11 at 01 14 50" src="https://user-images.githubusercontent.com/18720002/117698426-4e614200-b1f6-11eb-9cff-9129b900f54b.png">

**Comment by muhrizkiakbar** [comment]
i use worker and application job, application job for send notification and worker for creating data

**Comment by egeek** [comment]
Realise this is old and closed, but in case someone else finds it I just hit the same issue.

The problem turns out that we'd changed `ApplicationJob` so that it included `Sidekiq::Worker`, and sets some defaults. As soon as we did that the problem occurs. Removing these restores the correct behaviour.
