### ISSUE TITLE
Naming of the notification param in the 'email' delivery method

### ISSUE THREAD

**Issue by kylekeesling** [excid3/noticed#30]
I hope this doesn't come off as nit-picky, but I wanted to bring up/suggest a tweak to the naming of one of the mailer params in the `email` delivery method.

Since in my case I'm utilizing a polymorphic relationship to link up to the subject of my notifications, I was trying to find the best way to refer back to the notification record itself while building out my mailer action. Turns out there's a way to do this, and it's by referencing `params[:record]`.

In my head it seems a bit confusing to build out my mailer with a param called `:record` as opposed to `:notification`.

As it currently stands this is what I need to do:
```ruby
class CommentMailer < ApplicationMailer
  before_action do
    @recipient, @notification = params[:recipient], params[:record]
    @comment = @notification.notifiable
  ...
end
```

My proposal would be to change the params name to `:notification` so that in my mailers I could do this:
```ruby
class CommentMailer < ApplicationMailer
  before_action do
    @recipient, @notification = params[:recipient], params[:notification]
    @comment = @notification.notifiable
  ...
end
```

As I mentioned above I know this is a bit pedantic, but sometimes I feel that's half of what being a programmer is all about :)

I'm happy to submit a PR for this if you agree. From the looks of it I'd just need to make a change on this line:
https://github.com/excid3/noticed/blob/7c8c8b47fd45d92b2eb38d7561dd75614211894e/lib/noticed/delivery_methods/email.rb#L24

**Comment by excid3** [comment]
I think it's important to be clear there's a difference between the `notification` instance and the database record.

I've tried to keep it consistent by always calling the database record `record` and the noticed notification instance `notification`.

Definitely could be better naming for it, but I'm not sure what exactly. I don't think changing this to `:notification` make sense because it starts blending the two names.

**Comment by excid3** [comment]
If anything, we might just include the notification in the default params.

```ruby
notification.params.merge(
  notification: notification,
  recipient: recipient,
  record: record)
```

**Comment by kylekeesling** [comment]
Ah yes - that makes sense too. It just seems a bit jarring coming into the mailer where there is less context, but I completely understand.

**Comment by excid3** [comment]
Correct. The mailer should definitely get the notification instance passed over, overlooked that.

**Comment by kylekeesling** [comment]
Would it maybe make sense to just tweak the names to ':notification_record' and ':notification' then?

**Comment by excid3** [comment]
If that's the only place in the gem we use that name, I'd say no. I'd rather keep it consistent and use `record` here so it matches everything else.

**Comment by excid3** [comment]
Tried adding the `notification` tonight and I now remember why we don't have that. The notification object itself is not serializable by ActiveJob. Since we're sending mailers with `deliver_later`, the params must be serializable and those aren't, hence it's easier to use the notification method on the record.

**Comment by kylekeesling** [comment]
Ah makes sense - thanks for looking into this more. I've been able to move ahead as-is without any issues.
