### ISSUE TITLE
Unable to catch enqueued emails using config.active_job.queue_adapter = :test

### ISSUE THREAD

**Issue by olivierbuffon** [excid3/noticed#302]
Hey guys!

I'm going through a weird behaviour. I'm trying to test email notifications are correctly enqueued. 
I'm using ActiveJob, Rspec and `have_enqueued_mail` method.
The thing is, when I use `config.active_job.queue_adapter = :test` the test always fails saying no mail enqueued.
Alternatively, when I set the setting to :inline I go through the correct steps.

I can't figure out why... I might miss something but to be honest I'm a bit confused here 😆 !

Any idea or anyone experiencing the same thing? Thank!

**Comment by excid3** [comment]
Sending a notification enqueues a job for the notification, which then either sends the email immediately, or enqueues the mail delivery job. https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/email.rb#L8-L10

You'll first need to make sure that you process the notification job in order to see the email delivery method run.

**Comment by olivierbuffon** [comment]
🤔 Thanks for the answer, I'll double check! 🙏🏻

**Comment by olivierbuffon** [comment]
PS: @excid3 Also thanks for evertyhing you do for the RoR community ❤️ 🙏🏻
