### ISSUE TITLE
Unable to access root_url helper in Noticed classes

### ISSUE THREAD

**Issue by ap-hughes** [excid3/noticed#41]
I'm writing up an additional simple URL helper for Twilio messages to print the full url link so users can visit the site easily from their phones. I figure combing root_url and url_for should do the trick, but it doesn't seem I'm able to access the root_url helper in the Noticed classes.

I know you state in the readme URL helpers are here by default. I've tried including `Rails.application.routes.url_helpers` to check as well and prying in to the class and calling Rails.application.routes.url_helpers.root_url directly.

Error - `ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`

In my test, dev, and prod environments I have specified this (see dev example below), so I'm not sure why it can't access it here. Perhaps I'm missing something obvious - does it not use the below..?

`config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }`

**Comment by excid3** [comment]
Do you have an example I can use to reproduce?

**Comment by manojmj92** [comment]
Would be a good idea to also the check value of `Rails.application.routes.default_url_options` at the point of prying to make sure it has the values as expected.

**Comment by inopinatus** [comment]
This is normal for absolute URL generation in a non-request context. It might be fixed by https://github.com/rails/rails/issues/39566 but that isn't even necessarily going to make it into Rails 6.1.

Basically, when that error refers to `default_url_options`, it means a local method of that name, not a config variable.

Untested for Notifications (I don't have need of this just yet), but I wrote [this solution for Active Job](https://inopinatus.org/2015/09/08/using-url-helpers-in-rails-activejob-background-jobs/) back in 2015. Or you can just `root_url(host: 'example.com', protocol: 'https')`.

**Comment by ap-hughes** [comment]
Thank you for the all the help, I now have this working. I hadn't quite understood the nuances of url generation.

@manojmj92 - this returned an empty hash, so yes, would never have worked. Thanks for the heads up.

@inopinatus - thank you for providing context around this. I carried across the same logic described in your blog post and it has worked perfectly.
