### ISSUE TITLE
Strategy for fallback notifications?

### ISSUE THREAD

**Issue by swanson** [excid3/noticed#70]
Would be great to support (or document) how to handle this common use-case:

* Notify a user via `database` / in-app notification
* If user has not marked notification as read / seen after a certain time, notify via `email` or other channel.

**Comment by excid3** [comment]
Already supported, but not super well documented (since we just added it).

https://github.com/excid3/noticed#notification-objects

The `delay: 5.minutes` option can be added to a delivery method so it will be executed in a job 5 minutes after it was written to the database. The `if` `unless` callbacks are run then so you can cancel the email if they've already read it.

Need to add an example to the docs for it.

**Comment by swanson** [comment]
```ruby
class CommentNotification < Noticed::Base
  deliver_by :database
  deliver_by :email, mailer: 'CommentMailer', delay: 15.minutes, unless: :read?
end
```

Neat!
