### ISSUE TITLE
Usecases - what exactly should we use the gem for / scope of notifications

### ISSUE THREAD

**Issue by misner** [excid3/noticed#9]
Hey,

I'm a pretty newbie to RoR and coding in general.

First what is a database notification? i get what is an email, sms notification but not a database notification ? it's when you writes it to the database so next time a certain page is viewed by a user and you'll fetch this data to show him ?

I understand this is the core usecase when there is an external event that User1 is not aware as he did not initiate it himself. 

- if in a forum, user 2 comments the post of User 1, then we could use your Notification gem to notify User 1 with User's 2 message (in this case User1 is not at the source of the change triggering the notification)

- but what about if User1 performs an action such as post "5 messages in 10 days" and we consider this is a milestone, and let's say i want to send an email saying "congrats for doing 5 messages in 10 days",  should we use your "notification" gem for this ? as there is no "external" force (User2), are we in the concept of Notifications ? maybe I am misunderstanding the scope of Notifications: is it a concept that allow to simply structure things more cleanly than just a callback in a PostMessagescontroller?

- what about devise emails ? I guess emails sent in relation with authentication (ex: reset password, confirm email on sign up) are not to be used with noticed but rather already covered by devise gem

- notifications about new feature for everybody or a user segment... ? in your great [jumpstart Pro](https://jumpstartrails.com/) this is also covered by another part called Annoucements so I guess it's not the right usecase for Notifications.

- I see you adjusted the gem for jumpstart rails pro for multitenant cases: would you say it's the right use case if member 4 of team X edits the common Team X profile and so you add a email notification to certain members (ex those with admin roles) of team X with sth like "hey member 4 just edited the Team Profile) ? Again I'd just have used some callbacks on the TeamProfile Controller but maybe using notifications is cleaner ?

I know these questions must sound super naive but I find it hard to understand the scope/limits of what you call "Notifications".

Thanks for any help,
Cheers

**Comment by excid3** [comment]
Yes, most of the time you'll want to save a notification to the database, but not always so it's not a requirement. Useful for notification bells in the navbar.

You can setup a cron job if you'd like to send them a notification about "5 messages in 10 days". You'd have it run daily and count the number of messages and then send the notification. You'd need some other infrastructure on this so you're not sending that notification every single day, etc.

You could use it for similar use cases just like the Devise emails. Typically we're sending notifications to a user who is already in the database though, whereas Devise emails are not always. 

That said, you should be able to pass in a struct, hash or other object to Noticed to send notifications to places not in the database. Haven't tested that yet, but I don't think we have anything preventing it.

Notifications are typically for a specific user, so an announcement for everyone isn't typically what you'd want, but it could certainly work. You'd just be creating a lot of duplicate database records which is why I wouldn't recommend it for that.

If you wanted to notify team admins when something changed, that'd work perfect. You'd just figure out which users you wanted to notify and pass them along to Noticed.

Hope that helps!

**Comment by misner** [comment]
Thanks for your response.
thanks, got it!
